print("An upward pointing arrow implemented with 8 print statements")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****\n")

print("An upward pointing arrow implemented with two print statements")
print("    *\n", "   * *\n", "  *   *\n", " *     *", sep="")
print("***   ***\n", "  *   *\n", "  *   *\n", "  *****", sep="")

print("Dubling the size of the arrow")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("*****       *****")
print("    *       *")
print("    *       *")
print("    *       *")
print("    *       *")
print("    *********\n")

print("Duplicating the arrow")
print("        *          "*2)
print("       * *         "*2)
print("      *   *        "*2)
print("     *     *       "*2)
print("    *       *      "*2)
print("   *         *     "*2)
print("  *           *    "*2)
print(" *             *   "*2)
print("*****       *****  "*2)
print("    *       *      "*2)
print("    *       *      "*2)
print("    *       *      "*2)
print("    *********      "*2)

